/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

//https://howtodoinjava.com/hibernate/hibernate-hello-world-application/
package std_kotlin_postgre_hibernate

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
