/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

//https://howtodoinjava.com/hibernate/hibernate-hello-world-application/
package std_kotlin_postgre_hibernate

import std_kotlin_postgre_hibernate.db.TestHibernate
import java.util.logging.Level

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    TestHibernate().testDB()
    //TestHibernate().testDrop()
    println(App().greeting)
}
